
title: John Rogers
baseurl: ""
url: "http://jdrbc.ca"
github_username: jdrbc

# Build settings - minimal Jekyll configuration
plugins:
  - jekyll-sass-converter

# Include assets for processing
include:
  - assets

# Exclude unnecessary files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
